### ISSUE TITLE
Bugs?

### ISSUE THREAD

**Issue by JohnTailor** [mansweet/Gaussian-LDA-word2vec#2]
Thanks for the contribution. Not working with newer gensims (but easily fixable).
There is quite some unused but non-commented code. But that's kind of ok.
But the code is also buggy, e.g. used glove.6B.50d.txt and got: 

inf
Traceback (most recent call last):
  File "/home/wi-admin1/PycharmProjects/Gaussian-LDA-word2vec/GaussianLDA.py", line 242, in <module>
    g.fit(2)
  File "/home/wi-admin1/PycharmProjects/Gaussian-LDA-word2vec/GaussianLDA.py", line 105, in fit
    self.sample()
  File "/home/wi-admin1/PycharmProjects/Gaussian-LDA-word2vec/GaussianLDA.py", line 155, in sample
    print np.random.multinomial(1, pvals=posterior)
  File "mtrand.pyx", line 4617, in mtrand.RandomState.multinomial
ValueError: sum(pvals[:-1]) > 1.0

**Comment by un-lock-me** [comment]
@JohnTailor could you please explain how you resolve the last error u mentioned?

**Comment by JohnTailor** [comment]
I did not resolve it. I used another library, ie. the authors original Java implementation. Overall GaussianLDA did not work that well for my purpose, ie. comparing with my own topic model  https://github.com/JohnTailor/tkm .

**Comment by mansweet** [comment]
Sorry, I have not paid much attention to this old project of mine in a long time.  I would like to refactor and make it much more usable, now that I have much improved SWE chops.
